// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOyFEuYBtlsCigiuP5Hz_ZDt1SQ3kPYw',
    appId: '1:1044785373103:web:c30d8626cec9578b58595a',
    messagingSenderId: '1044785373103',
    projectId: 'ad-ad-ce821',
    authDomain: 'ad-ad-ce821.firebaseapp.com',
    storageBucket: 'ad-ad-ce821.appspot.com',
    measurementId: 'G-CWXYNN3VHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCNImexAGwUMWoxMUjC3OBsdDsXumfYo',
    appId: '1:1044785373103:android:5645258ab22bf85b58595a',
    messagingSenderId: '1044785373103',
    projectId: 'ad-ad-ce821',
    storageBucket: 'ad-ad-ce821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAej7cNSnwH1SWkiLrQSzMrgd49PZfawJA',
    appId: '1:1044785373103:ios:42a473847bab321c58595a',
    messagingSenderId: '1044785373103',
    projectId: 'ad-ad-ce821',
    storageBucket: 'ad-ad-ce821.appspot.com',
    iosBundleId: 'com.example.adAd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAej7cNSnwH1SWkiLrQSzMrgd49PZfawJA',
    appId: '1:1044785373103:ios:c22b00cc4e9a4e8d58595a',
    messagingSenderId: '1044785373103',
    projectId: 'ad-ad-ce821',
    storageBucket: 'ad-ad-ce821.appspot.com',
    iosBundleId: 'com.example.adAd.RunnerTests',
  );
}
